--------------------------------------------------------
--  Fichier créé - mercredi-avril-28-2021   
--------------------------------------------------------
DROP TABLE "MALEK"."COMMANDE";
DROP TABLE "MALEK"."RESERVATION";
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "MALEK"."COMMANDE" 
   (	"CODE" NUMBER, 
	"PRIX" NUMBER, 
	"CP" NUMBER, 
	"QT" NUMBER, 
	"NUM_TELC" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "MALEK"."RESERVATION" 
   (	"ID_R" NUMBER, 
	"NUM_TEL" NUMBER, 
	"NBR_PR" NUMBER, 
	"DAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MALEK.COMMANDE
SET DEFINE OFF;
Insert into MALEK.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,NOM,DATC) values ('44','55555','66666','555','55555','nour','01-JAN-00');
Insert into MALEK.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,NOM,DATC) values ('12','1','1','1','11111111',null,'01-JAN-00');
REM INSERTING into MALEK.RESERVATION
SET DEFINE OFF;
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('0','0','0','01-JAN-00');
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('12','985623','666','01-JAN-00');
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('44','2','2','01-JAN-00');
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('88','88','88','01-JAN-00');
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('5','1','1','01-JAN-00');
Insert into MALEK.RESERVATION (ID_R,NUM_TEL,NBR_PR,DAT) values ('789','4555','45','01-JAN-00');
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."COMMANDE_PK" ON "MALEK"."COMMANDE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."RESERVATION_PK" ON "MALEK"."RESERVATION" ("ID_R") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."COMMANDE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "MALEK"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID_R")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."RESERVATION" MODIFY ("ID_R" NOT NULL ENABLE);
